// get list pokés
export const GET_LIST_POKEMON_REQUEST = 'GET_LIST_POKEMON_REQUEST'
export const GET_LIST_POKEMON_REQUEST_SUCCESS = 'GET_LIST_POKEMON_REQUEST_SUCCESS'
export const GET_LIST_POKEMON_REQUEST_FAIL = 'GET_LIST_POKEMON_REQUEST_FAIL'

//login
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL'

//register
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS'
export const SIGNUP_REQUEST_FAIL = 'SIGNUP_REQUEST_FAIL'

//get list user
export const GET_LIST_ACCOUNT_REQUEST = 'GET_LIST_ACCOUNT_REQUEST'
export const GET_LIST_ACCOUNT_SUCCESS = 'GET_LIST_ACCOUNT_SUCCESS'
export const GET_LIST_ACCOUNT_FAIL = 'GET_LIST_ACCOUNT_FAIL'
